---
  config:
    class:
      hideEmptyMembersBox: true
---

classDiagram
    class App {
        <<interface>>
        +setView(view: View)
        +exportToGame()
        +returnToEditor()
    }

    App *.. GameController
    App *.. EditorController

    class EditorController {
        <<interface>>
        +place()
        +remove()
    }

    class GameController {
        <<interface>>
        +startGame()
        +stopGame()
    }

    GameController *-- GameEngine

    class GameEngine {
        <<interface>>
    }

    class GameObjectType {
        <<enumeration>>
        BLOCK
        ACTOR
        COLLECTABLE
    }

    class GameObject {
        <<interface>>
        +getType() GameObjectType
    }
    GameObject --* GameObjectType


    class EditorGrid {
        <<interface>>
    }
    class EditorMenu {
        <<interface>>
    }

    EditorController *.. EditorMenu
    EditorController *.. EditorGrid

    EditorMenu o-- GameObject
    EditorGrid o-- GameObject
    GameEngine o-- GameObject

    Player --|> GameObject
    Wall --|> GameObject
    Floor --|> GameObject
    End --|> GameObject
    Spike --|> GameObject
    Coin --|> GameObject
