name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: oracle

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run static checks and tests
      run: ./gradlew check
